== Step
The step is the basic element to create a test. A test normally is an aggregation of several steps.

There are two types of steps::

* single +
  This step will be executed once for all the test cases.

* normal +
	In this case there will be instantiate one step object per test case.

=== Configuration
When creating a step the following configurations are supported.

* type +
  The type of this step. {normal|single}

* name +
  The name of this step

* needData +
	Normally a step will only be executed if there is a test case which defines data
	for this step. But some steps do not need any data. For example there is a step
	which cleans a data base.

=== Properties
This describes the existing properties of a step and what there are used for.

* logger +
  The logger used to log. This logger should be used in the step implementation.

* stepInstanceId +
  A UUID for the instance of the step. This is is used to correlate logs later on.

* environmentTestcase +
  A step could store and retrieve data from this environment. This context lives as long
  the test case. So a step could pass data to one of the next steps.
  If this is a singleStep, then this is an array of environments

* environmentRun +
  A context shared between all the test cases.

* name +
  Just the name for this step.

* testMode +
  The idea of the test mode is to test the run of a step without executing it completly.
  So the suite could be tested. This is important for long running tests

* status +
  The status of this step while execution

* data +
  The test data for this step instance. If this is a single step, then this is an array
  of data.

=== Log methods
These methods are for step implementer.

Parameter for all the log messages.

* message +
  The message or object to log.

* RETURNS +
  A promise when the log was written.


List of all the log messages::
 * logDebug(message)
 * logInfo(options)
 * logWarning(options)
 * logError(options)
 * logFatal(options)

=== Methods called by the runner
These methods could be implemented by the step implementer.
They will be called by the runner while step execution

Each of the methods must return a promise.


==== start()
This method is called for all the step instances
when a new step is entered in the execution.

==== beforeRun()
This method will be called just before the run method is called. This
method is called per test case.


==== run()
The run method is the method which should do the work of the step.

==== afterRun()
This method will be called just after the run method is finished.
It will be called even if the run method has failed. So this method
could be used for clean up.

==== end()
This method will be called when all the step instances of this step are finished.
